FROM python:3.10.6-buster

COPY api.py /api.py
COPY functions.py /functions.py
COPY .env /.env
COPY Private /Private
COPY  DEMO_DATASET /DEMO_DATASET
COPY models /models
COPY requirements.txt /requirements.txt

ENV GOOGLE_APPLICATION_CREDENTIALS="Private/le-wagon-bootcamp-392422-faf9e335c10d.json"

RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN python3 -m spacy download en_core_web_md

CMD uvicorn api:app --host 0.0.0.0 --port $PORT
#CMD uvicorn api:app --host 0.0.0.0
